objects=Command.class CommandEvt.class CommandTypes.class Condition.class ConditionEvt.class Constants.class Dec.class DecList.class ForLoop.class HeadLoop.class Load.class LoadParser.class Loop.class LoopEvt.class Lsym.class ResizeException.class StrukElement.class StrukElementEvt.class StrukElementEvtPopUp.class StruktogrammAppEvt.class Struktogramm.class StruktogrammEvt.class StruktogrammView.class Switch.class SwitchEvt.class SwitchValue.class TailLoop.class WatchList.class Yylex.class 

CLASSPATH = ../..

.PHONY: all

all : $(objects)

StrukElementEvtPopUp.class: StrukElementEvtPopUp.java
	javac -classpath $(CLASSPATH) StrukelementEvt.java

$(objects): $(subst .class,.java,$(objects))
	javac -classpath $(CLASSPATH) $(subst .class,.java,$@)

StrukElementEvtPopUp.class: StrukElementEvtPopUp.java
	javac -classpath $(CLASSPATH) StrukelementEvt.java



clean:
	-rm *.class
