
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 11 16:18:13 CET 2005
//----------------------------------------------------

package struktor.strukelements;

/** CUP generated class containing symbol constants. */
public class Lsym {
  /* terminals */
  public static final int INPUT = 20;
  public static final int ELSE = 13;
  public static final int SEMI = 2;
  public static final int WHILE = 14;
  public static final int SWITCH = 17;
  public static final int IF = 12;
  public static final int DO = 15;
  public static final int CONDITION = 23;
  public static final int ENDSTRUK = 10;
  public static final int STRING = 27;
  public static final int REPAR = 7;
  public static final int COMMA = 3;
  public static final int ADMSG = 21;
  public static final int EOF = 0;
  public static final int RSPAR = 5;
  public static final int BREAK = 31;
  public static final int STARTSTRUK = 26;
  public static final int VARNAME = 25;
  public static final int CASE = 28;
  public static final int error = 1;
  public static final int POINTER = 11;
  public static final int ASSIGN = 9;
  public static final int COMMAND = 22;
  public static final int LEPAR = 6;
  public static final int INTEGER = 30;
  public static final int VARTYPE = 29;
  public static final int DEFAULT = 18;
  public static final int RPAR = 8;
  public static final int FOR = 16;
  public static final int OUTPUT = 19;
  public static final int LSPAR = 4;
  public static final int STRUKNAME = 24;
  public static final int DOUBLE = 32;
}

