CLASSPATH = ../../..

objects := $(patsubst %.class,%.java,$(wildcard *.class))

all: Pointer.class Datatype.class

Datatype.class: Datatype.java
	javac -classpath $(CLASSPATH) Datatype.java

Pointer.class: Pointer.java
	javac -classpath $(CLASSPATH) Pointer.java

clean:
	-rm *.class
