#
# Makefile created at Sun Apr 27 01:21:23 2003, by mmake
# altered by Kim Sun Apr 27
# 

# Programs (with common options):
SHELL		= /bin/sh
RM              = rm -f
MV              = mv -f
SED		= sed
XARGS		= xargs
CAT		= cat
FIND            = find
CPP		= cpp -C -P

INSTALL         = install
INSTALL_PROG    = $(INSTALL) -m $(MODE_PROGS)
INSTALL_FILE    = $(INSTALL) -m $(MODE_FILES)
INSTALL_DIR     = $(INSTALL) -m $(MODE_DIRS) -d

# Install modes 
MODE_PROGS      = 555
MODE_FILES      = 444
MODE_DIRS       = 2755

# Build programs
JAVAC           = javac
JAVADOC         = javadoc
JAR             = jar

# Build flags
JAVAC_FLAGS     = 
JAVADOC_FLAGS   = -version -author -private
JAR_FLAGS       = cvf

# ------------------------------------------------------------------- #

#for Debian GNU/Linux
DESTDIR=

# Prefix original
ifneq ($(DESTDIR),)
	prefix_orig=/usr/
else
	prefix_orig=/usr/local/
endif

# Prefix for every install directory
prefix		= ${DESTDIR}${prefix_orig}

# The directory to install the jar file in. Set this to an empty value
#  if you dont want to install a jar file
#  it's a relative directory because of the difference when generating the
#  wrapper script at the script-target (see below)
JAR_DIR	        = share/java

# The directory to install man files
MAN_DIR		= share/man/man1

# The directory to install html files generated by javadoc
DOC_DIR         = $(prefix)doc

# The directory to install script files in
SCRIPT_DIR	= $(prefix)bin

# ------------------------------------------------------------------- #

VERSION         = 0.62


# The name of the jar file to install
JAR_FILE        = struktor-$(VERSION).jar


# ------------------------------------------------------------------- #


# Packages we should compile
PACKAGES = \
	struktor.gui \
	struktor.strukelements \
	struktor.processor.functions \
	struktor.processor.operators \
	struktor.processor.datatypes \
	struktor \
	struktor.util \
	struktor.processor \



# ------------------------------------------------------------------- #

# A marker variable for the top level directory
TOPLEVEL	:= struktor

# Subdirectories with java files:
JAVA_DIRS	:= $(subst .,/,$(PACKAGES)) $(TOPLEVEL)

# All the .java source files:
JAVA_SRC	:= $(foreach dir, $(JAVA_DIRS), $(wildcard $(dir)/*.java))

# Dependency files:
DEPEND_OBJS	:= $(JAVA_SRC:.java=.u)

# Objects that should go into the jar file. (find syntax)
JAR_OBJS	:= \( -name '*.class' -o -name '*.jpg' -o -name "*.au" \
		       -o -name '*.properties' \)

# The intermediate java files and main classes we should build:
JAVA_OBJS	:= $(JAVA_SRC:.java=.class)

# All dynamically build script-objects (only the wrapper up to now)
SCRIPT_OBJS	:= struktorstart

# Escape inner class delimiter $
INSTALL_OBJS	:= $(subst $$,\$$,$(INSTALL_OBJS))

# ------------------------------------------------------------------- #


define check-exit
|| exit 1

endef

# ---------------
#  Default Target
#  --------------

all::	$(JAVA_OBJS) $(JAR_FILE)

# -----------
# Build Rules
# -----------

#struktor/Presets.class: struktor/Presets.java
#	perl -p -i.bak -e 's/(static public final String version)="\d+\.\d+";/\1="$(VERSION)";/g' struktor/Presets.java
#	javac struktor/Presets.java

%.class: %.java
	$(JAVAC) $(JAVAC_FLAGS) $<

%.jar: $(JAVA_OBJS) 
	@echo "===> [Generating jar-file] "
	$(FIND) $(TOPLEVEL) $(JAR_OBJS) -print | $(XARGS) \
	$(JAR) $(JAR_FLAGS) $(JAR_FILE) 
	@echo "===> [Generating java-cup runtime jar] "
	$(JAR) $(JAR_FLAGS) javacup_runtime.jar java_cup/runtime/*.class

./man/struktor.1.gz: man/struktor.pod 
	@echo "===> [Generating man-page] "
	pod2man --section=1 --center=Nassi-Shneiderman-Editor man/struktor.pod > man/struktor.1
	cat man/struktor.1 | gzip -9 > man/struktor.1.gz

%.u: %.java
	$(JAVAC) $(JIKES_DEP_FLAG) $<


# -------
# Targets
# -------

.PHONY: all jar man install uninstall doc clean depend tags

help:
	@echo "Usage: make {all|jar|man|install|uninstall|doc|clean}"

# Jar target
jar:	$(JAR_FILE) javacup_runtime.jar
install:: $(JAR_FILE) javacup_runtime.jar
	@echo "===> [Installing jar file, $(JAR_FILE) in $(prefix)$(JAR_DIR)] "
	$(INSTALL_DIR) $(prefix)$(JAR_DIR) $(check-exit)
	$(INSTALL_FILE) $(JAR_FILE) $(prefix)$(JAR_DIR) $(check-exit)
	@echo "===> [Installing javacup_runtime jar file in $(prefix)$(JAR_DIR)] "
	$(INSTALL_FILE) javacup_runtime.jar $(prefix)$(JAR_DIR) $(check-exit)
uninstall::
	@echo "===> [Removing jar file, $(JAR_FILE) from $(prefix)$(JAR_DIR)] "
	$(RM) $(prefix)$(JAR_DIR)/$(JAR_FILE)  $(check-exit)
	@echo "===> [Removing javacup_runtime jar file from $(prefix)$(JAR_DIR)] "
	$(RM) $(prefix)$(JAR_DIR)/javacup_runtime.jar $(check-exit)
clean::
	@echo "===> [cleaning up ... jar-files]"
	$(RM) $(JAR_FILE)
	$(RM) javacup_runtime.jar

# man target
man:	man/struktor.1.gz
install:: man/struktor.1.gz
	@echo "===> [Installing man file, man/struktor.1.gz in $(prefix)$(JAR_DIR)] "
	$(INSTALL_DIR) $(prefix)$(MAN_DIR)
	$(INSTALL_FILE) man/struktor.1.gz $(prefix)$(MAN_DIR) $(check-exit)
uninstall::
	@echo "===> [Removing man file, struktor.1.gz from $(prefix)$(MAN_DIR)] "
	$(RM) $(prefix)$(MAN_DIR)/struktor.1.gz
clean::
	echo "===> [cleaning up ... man-files]"
	$(RM) man/struktor.1.gz man/struktor.1


# Doc target
doc:	$(JAVA_SRC)
	@echo "===> [Generating java documentation in doc] "
	if [ ! -d doc ]; then mkdir doc; fi
	$(JAVADOC) -d doc $(JAVADOC_FLAGS) $(PACKAGES)
clean::
	echo "===> [cleaning up ... doc-directory]"
	$(RM) -r doc



# Script target
all::	
	@echo "===> [Generating shell-wrapper] "
	echo "#!/bin/bash" > struktorstart
	echo "[ ! -z \$$1 ] && [ \$$1 = "--version" ] && echo "struktor $(VERSION)" && exit fi" >> struktorstart
	echo "java -cp struktor-$(VERSION).jar:javacup_runtime.jar struktor.StruktorApplication \$$1" >> struktorstart
	chmod u+x struktorstart
install:: 
	@echo "===> [Generating shell-script] "
	echo "#!/bin/bash" > struktor.temp
	echo "[ \$$1 = "--version" ] && echo "struktor $(VERSION)" && exit" >> struktor.temp
	echo "java -cp $(prefix_orig)$(JAR_DIR)/$(JAR_FILE):$(prefix_orig)$(JAR_DIR)/javacup_runtime.jar struktor.StruktorApplication \$$1" >>  struktor.temp
	@echo "===> [Installing shell-scripts in $(SCRIPT_DIR)] "
	$(INSTALL_DIR) $(SCRIPT_DIR) $(check-exit)
	$(INSTALL_PROG) struktor.temp $(SCRIPT_DIR) $(check-exit)
	rm struktor.temp
	mv $(SCRIPT_DIR)/struktor.temp $(SCRIPT_DIR)/struktor
uninstall:: 
	@echo "===> [Removing shell-scripts from $(SCRIPT_DIR)] "
	$(RM) $(SCRIPT_DIR)/struktor $(check-exit))
clean::
	@echo "===> [cleaning up ... script-files]"
	rm -f $(SCRIPT_OBJS)



# Various cleanup routines
clean::
	@echo "===> [cleaning up ... various-files]"
	$(FIND) . \( -name '*~' -o -name '*.class' \) -print | \
	$(XARGS) $(RM) 
	$(FIND) . -name '*.u' -print | $(XARGS) $(RM)
