
VERSION = 0.6
JAR-APPENDIX = -$(VERSION)
DESTDIR =
INST-TARGET-DIR = $(DESTDIR)/usr/local

.PHONY: all wrapper jar struktor proclexer loadlexer java_cup jlex doc docclean cleanall clean

all: jlex java_cup loadlexer proclexer struktor jar wrapper

wrapper:
	echo "#!/bin/bash" > struktorstart
	echo "java -cp . struktor.StruktorApplication" >> struktorstart
	chmod u+x struktorstart

jar: 
	jar -cf struktor$(JAR-APPENDIX).jar $(shell find struktor -type d -exec echo {}/*.class \;)
	jar -uf struktor$(JAR-APPENDIX).jar struktor/Logo.JPG

struktor:
	$(MAKE) -C struktor


proclexer:
	$(MAKE) -C ProcLexerFactory
	$(MAKE) -C ProcLexerFactory install

loadlexer:
	$(MAKE) -C LoadLexerFactory
	$(MAKE) -C LoadLexerFactory install

java_cup:
	$(MAKE) -C java_cup

jlex:
	$(MAKE) -C JLex

install:
	$(shell if [ ! -d $(INST-TARGET-DIR)/share/java ]; then \
	 	if [ ! -d $(INST-TARGET-DIR)/share ]; then \
			mkdir $(INST-TARGET-DIR)/share ; \
		fi; \
		mkdir mkdir $(INST-TARGET-DIR)/share/java ; \
	fi;)
	cp struktor$(JAR-APPENDIX).jar $(INST-TARGET-DIR)/share/java/struktor$(JAR-APPENDIX).jar
	echo "#!/bin/bash" > $(INST-TARGET-DIR)/bin/struktor
	echo "java -cp $(INST-TARGET-DIR)/share/java/struktor$(JAR-APPENDIX).jar struktor.StruktorApplication" >>  $(INST-TARGET-DIR)/bin/struktor
	chmod u+x,g+x,o+x $(INST-TARGET-DIR)/bin/struktor

uninstall:
	-rm $(INST-TARGET-DIR)/bin/struktor
	-rm $(INST-TARGET-DIR)/share/java/struktor$(JAR-APPENDIX).jar

doc:
	mkdir doc
	javadoc -d doc struktor struktor.gui struktor.processor struktor.processor.datatypes struktor.processor.functions struktor.processor.operators struktor.strukelements

docclean:
	-rm -r doc
	
clean:
	-rm *.jar
	-rm struktorstart

cleanall: clean
	 $(shell find struktor -name "*.class" -exec rm {} \;)
