objects= CAcceptAnchor.class CAccept.class CAlloc.class CBunch.class CDfa.class CDTrans.class CEmit.class CError.class CInput.class CLexGen.class CMakeNfa.class CMinimize.class CNfa2Dfa.class CNfa.class CNfaPair.class CSet.class CSimplifyNfa.class CSpec.class CUtility.class Main.class SparseBitSet$$1.class SparseBitSet$$2.class SparseBitSet$$3.class SparseBitSet$$4.class SparseBitSet$$BinOp.class SparseBitSet.class 

all: $(objects)

$(objects) :  Main.java
	javac Main.java 

clean:
	rm *.class
