/* The following code was generated by JFlex 1.4.1 on 10.02.07 18:15 */

package struktor.processor;

import java_cup.runtime.ComplexSymbolFactory;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 10.02.07 18:15 from the specification file
 * <tt>/home/kim/src/workspace/struktor.svn.sf.net/parser/processor.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 1;
  public static final int ARRAY3 = 4;
  public static final int ARRAY2 = 3;
  public static final int YYINITIAL = 0;
  public static final int ARRAY1 = 2;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  3, 46,  6,  0, 45, 45,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    46, 18,  5,  0, 42, 16, 22, 44, 14, 15, 11, 10, 40,  7, 12, 13, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  9, 19, 17, 20,  0, 
     0,  2,  2,  2,  2,  8,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 41,  4, 43,  0,  2, 
     0, 33, 29, 35, 26, 31, 38,  2, 39, 23,  2, 34, 30,  2, 24, 27, 
     2,  2, 32, 36, 25, 28,  2,  2,  2,  2, 37,  0, 21,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\4"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\4\1\25"+
    "\6\6\1\26\1\27\1\4\1\14\4\0\1\1\1\2"+
    "\1\3\1\0\1\30\1\31\1\32\2\0\1\33\1\34"+
    "\1\35\2\0\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\7\6\1\44\5\0\1\30\2\0\1\33\3\0\1\45"+
    "\6\6\1\46\6\0\1\47\4\6\1\50\1\6\3\0"+
    "\1\51\1\0\1\6\1\52\2\6\1\53\1\6\1\52"+
    "\3\0\1\54\1\55\2\6\1\55\2\0\1\56\1\6"+
    "\1\57\1\0\1\60\2\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\353\0\u01a7\0\353\0\u01d6\0\353\0\u0205\0\353"+
    "\0\u0234\0\353\0\353\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f"+
    "\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468\0\353"+
    "\0\u0497\0\u04c6\0\353\0\u031f\0\u04f5\0\u0524\0\u0553\0\353"+
    "\0\353\0\353\0\u0582\0\u05b1\0\353\0\353\0\u0178\0\u05e0"+
    "\0\353\0\353\0\353\0\u060f\0\u063e\0\353\0\353\0\353"+
    "\0\353\0\353\0\353\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729"+
    "\0\u0758\0\u0787\0\353\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872"+
    "\0\u08a1\0\u08a1\0\u08d0\0\u0178\0\u08ff\0\u092e\0\u095d\0\u098c"+
    "\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\353\0\u0ad5"+
    "\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\353\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\353"+
    "\0\u0d96\0\u0dc5\0\u0149\0\u0df4\0\u0e23\0\353\0\u0e52\0\353"+
    "\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0149\0\u0f3d\0\u0f6c\0\353"+
    "\0\u0f9b\0\u0fca\0\353\0\u0ff9\0\353\0\u1028\0\353\0\u0149"+
    "\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\2\6\1\11\1\12\1\13\1\10"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\2\10"+
    "\1\33\2\10\1\34\2\10\1\35\2\10\1\36\1\37"+
    "\3\10\1\40\2\6\1\41\1\42\2\12\7\0\1\13"+
    "\1\0\1\14\1\15\1\16\1\43\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\44\1\31\6\0"+
    "\1\45\2\0\1\46\2\0\1\47\22\0\1\13\1\0"+
    "\1\14\1\15\1\16\1\43\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\44\1\31\6\0\1\45"+
    "\2\0\1\46\2\0\1\47\6\0\1\50\13\0\1\13"+
    "\1\0\1\14\1\15\1\16\1\43\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\44\1\31\6\0"+
    "\1\45\2\0\1\46\2\0\1\47\6\0\1\51\13\0"+
    "\1\13\1\0\1\14\1\15\1\16\1\43\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\44\1\31"+
    "\6\0\1\45\2\0\1\46\2\0\1\47\6\0\1\52"+
    "\64\0\1\7\6\0\1\53\3\0\1\54\22\0\1\53"+
    "\20\0\2\10\5\0\1\10\5\0\1\55\10\0\21\10"+
    "\1\0\1\56\5\0\4\57\1\60\1\61\1\0\50\57"+
    "\7\0\1\62\61\0\1\63\45\0\1\54\104\0\1\64"+
    "\2\0\1\65\45\0\1\66\56\0\1\67\56\0\1\70"+
    "\56\0\1\71\62\0\1\72\57\0\1\73\31\0\2\10"+
    "\5\0\1\10\5\0\1\55\10\0\1\10\1\74\17\10"+
    "\1\0\1\56\6\0\2\10\5\0\1\10\5\0\1\55"+
    "\10\0\4\10\1\75\14\10\1\0\1\56\6\0\2\10"+
    "\5\0\1\10\5\0\1\55\10\0\11\10\1\76\7\10"+
    "\1\0\1\56\6\0\2\10\5\0\1\10\5\0\1\55"+
    "\10\0\10\10\1\77\10\10\1\0\1\56\6\0\2\10"+
    "\5\0\1\10\5\0\1\55\10\0\4\10\1\100\13\10"+
    "\1\101\1\0\1\56\6\0\2\10\5\0\1\10\5\0"+
    "\1\55\10\0\1\102\20\10\1\0\1\56\56\0\1\103"+
    "\5\0\4\104\1\105\2\0\50\104\40\0\1\106\55\0"+
    "\1\107\52\0\1\110\24\0\1\111\5\0\1\112\2\0"+
    "\1\112\45\0\1\54\6\0\1\53\26\0\1\53\17\0"+
    "\3\57\1\113\1\60\1\114\1\115\47\57\1\113\30\0"+
    "\1\116\61\0\1\117\24\0\2\10\5\0\1\10\5\0"+
    "\1\55\10\0\2\10\1\120\16\10\1\0\1\56\6\0"+
    "\2\10\5\0\1\10\5\0\1\55\10\0\5\10\1\121"+
    "\13\10\1\0\1\56\6\0\2\10\5\0\1\10\5\0"+
    "\1\55\10\0\10\10\1\122\10\10\1\0\1\56\6\0"+
    "\2\10\5\0\1\10\5\0\1\55\10\0\2\10\1\123"+
    "\16\10\1\0\1\56\6\0\2\10\5\0\1\10\5\0"+
    "\1\55\10\0\1\10\1\124\17\10\1\0\1\56\6\0"+
    "\2\10\5\0\1\10\5\0\1\55\10\0\12\10\1\125"+
    "\6\10\1\0\1\56\6\0\2\10\5\0\1\10\5\0"+
    "\1\55\10\0\16\10\1\126\2\10\1\0\1\56\61\0"+
    "\1\127\5\0\1\130\1\0\1\104\1\130\45\0\1\127"+
    "\1\0\1\130\37\0\1\131\50\0\1\132\55\0\1\133"+
    "\27\0\1\111\55\0\3\57\1\113\1\60\1\61\1\115"+
    "\47\57\1\113\3\0\1\115\1\57\1\0\1\115\47\0"+
    "\1\115\31\0\1\134\61\0\1\135\23\0\2\10\5\0"+
    "\1\10\2\0\1\136\2\0\1\55\10\0\21\10\1\0"+
    "\1\56\6\0\2\10\5\0\1\10\5\0\1\55\10\0"+
    "\6\10\1\137\12\10\1\0\1\56\6\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\12\10\1\140\6\10\1\0"+
    "\1\56\6\0\2\10\5\0\1\10\5\0\1\55\10\0"+
    "\5\10\1\141\13\10\1\0\1\56\6\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\2\10\1\142\16\10\1\0"+
    "\1\56\6\0\2\10\5\0\1\10\5\0\1\55\10\0"+
    "\11\10\1\143\7\10\1\0\1\56\6\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\10\10\1\144\10\10\1\0"+
    "\1\56\10\0\1\130\1\104\1\0\1\130\47\0\1\130"+
    "\41\0\1\145\51\0\1\146\53\0\1\147\44\0\1\150"+
    "\74\0\1\151\22\0\2\10\5\0\1\10\5\0\1\55"+
    "\10\0\7\10\1\152\11\10\1\0\1\56\6\0\2\10"+
    "\5\0\1\10\5\0\1\55\10\0\13\10\1\153\5\10"+
    "\1\0\1\56\6\0\2\10\5\0\1\10\5\0\1\55"+
    "\10\0\11\10\1\154\7\10\1\0\1\56\6\0\2\10"+
    "\5\0\1\10\5\0\1\55\10\0\1\155\20\10\1\0"+
    "\1\56\6\0\2\10\5\0\1\10\2\0\1\156\2\0"+
    "\1\55\10\0\21\10\1\0\1\56\6\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\4\10\1\157\14\10\1\0"+
    "\1\56\47\0\1\160\54\0\1\161\45\0\1\162\65\0"+
    "\1\163\21\0\2\10\5\0\1\10\5\0\1\55\10\0"+
    "\10\10\1\164\10\10\1\0\1\56\6\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\1\10\1\165\17\10\1\0"+
    "\1\56\6\0\2\10\5\0\1\10\5\0\1\55\10\0"+
    "\1\10\1\166\17\10\1\0\1\56\6\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\17\10\1\167\1\10\1\0"+
    "\1\56\35\0\1\170\56\0\1\171\65\0\1\172\20\0"+
    "\2\10\5\0\1\10\2\0\1\173\2\0\1\55\10\0"+
    "\21\10\1\0\1\56\6\0\2\10\5\0\1\10\5\0"+
    "\1\55\10\0\5\10\1\174\13\10\1\0\1\56\6\0"+
    "\2\10\5\0\1\10\5\0\1\175\10\0\21\10\1\0"+
    "\1\56\41\0\1\176\41\0\1\177\40\0\2\10\5\0"+
    "\1\10\5\0\1\55\10\0\10\10\1\200\10\10\1\0"+
    "\1\56\44\0\1\201\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4183];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\3\1\1\11\3\1\1\11\1\1\1\11\1\1"+
    "\1\11\1\1\1\11\1\1\2\11\14\1\1\11\2\1"+
    "\1\11\4\0\3\11\1\0\1\1\2\11\2\0\3\11"+
    "\2\0\6\11\7\1\1\11\5\0\1\1\2\0\1\1"+
    "\3\0\7\1\1\11\6\0\1\11\6\1\3\0\1\11"+
    "\1\0\4\1\1\11\1\1\1\11\3\0\4\1\1\11"+
    "\2\0\1\11\1\1\1\11\1\0\1\11\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
// remember the last occured identifier for Array support
private String identifier = null;
private ComplexSymbolFactory symFact;

Yylex(java.io.Reader in, ComplexSymbolFactory symFact) {
	this(in);
	this.symFact=symFact;
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, ProcessorException
 {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 47: 
          { return symFact.newSymbol("sizeof(",Psym.SIZEOF);
          }
        case 50: break;
        case 5: 
          { return symFact.newSymbol("anInt",Psym.INTEGER, new Integer(yytext()));
          }
        case 51: break;
        case 41: 
          { return symFact.newSymbol("(int)",Psym.INTCAST);
          }
        case 52: break;
        case 15: 
          { return symFact.newSymbol(")",Psym.RPAREN);
          }
        case 53: break;
        case 12: 
          { return symFact.newSymbol(".",Psym.PART);
          }
        case 54: break;
        case 45: 
          { return symFact.newSymbol("return",Psym.RET);
          }
        case 55: break;
        case 23: 
          { yybegin(YYINITIAL); return symFact.newSymbol("]",Psym.RPAREN);
          }
        case 56: break;
        case 38: 
          { return symFact.newSymbol("aChar",Psym.CHARACTER, new Character(yytext().charAt(1)));
          }
        case 57: break;
        case 35: 
          { return symFact.newSymbol("&&",Psym.LOGAND);
          }
        case 58: break;
        case 22: 
          { return symFact.newSymbol("aParameter",Psym.PARAM);
          }
        case 59: break;
        case 4: 
          { throw new ProcessorException("Illegal Character: "+yytext());
          }
        case 60: break;
        case 44: 
          { return symFact.newSymbol("double",Psym.TYPENAME, new String("double"));
          }
        case 61: break;
        case 7: 
          { /* ignore white space. */
          }
        case 62: break;
        case 49: 
          { return symFact.newSymbol("continue",Psym.CONTINUE);
          }
        case 63: break;
        case 43: 
          { return symFact.newSymbol("char*",Psym.TYPENAME, new String("char*"));
          }
        case 64: break;
        case 10: 
          { return symFact.newSymbol("+",Psym.PLUS);
          }
        case 65: break;
        case 9: 
          { return symFact.newSymbol(";",Psym.SEMI);
          }
        case 66: break;
        case 37: 
          { return symFact.newSymbol("int",Psym.TYPENAME, new String("int"));
          }
        case 67: break;
        case 34: 
          { return symFact.newSymbol("||",Psym.LOGOR);
          }
        case 68: break;
        case 21: 
          { return symFact.newSymbol("&",Psym.ADRESS);
          }
        case 69: break;
        case 3: 
          { yybegin(YYINITIAL); return symFact.newSymbol("+",Psym.PLUS);
          }
        case 70: break;
        case 19: 
          { return symFact.newSymbol("<",Psym.LES);
          }
        case 71: break;
        case 1: 
          { yybegin(ARRAY2); return symFact.newSymbol("arrayIndex",Psym.LPAREN);
          }
        case 72: break;
        case 24: 
          { return symFact.newSymbol("aDouble",Psym.DOUBLE, new Double(yytext()));
          }
        case 73: break;
        case 39: 
          { return symFact.newSymbol("int*",Psym.TYPENAME, new String("int*"));
          }
        case 74: break;
        case 28: 
          { return symFact.newSymbol("--",Psym.DEC);
          }
        case 75: break;
        case 46: 
          { return symFact.newSymbol("double*",Psym.TYPENAME, new String("double*"));
          }
        case 76: break;
        case 17: 
          { return symFact.newSymbol("=",Psym.ASSIGN);
          }
        case 77: break;
        case 31: 
          { return symFact.newSymbol("!=",Psym.NEQ);
          }
        case 78: break;
        case 2: 
          { yybegin(ARRAY3); return symFact.newSymbol("arrayIndex",Psym.VARIABLE, identifier);
          }
        case 79: break;
        case 14: 
          { return symFact.newSymbol("(",Psym.LPAREN);
          }
        case 80: break;
        case 13: 
          { return symFact.newSymbol("/",Psym.DIVIDE);
          }
        case 81: break;
        case 48: 
          { return symFact.newSymbol("(double)",Psym.DOUBLECAST);
          }
        case 82: break;
        case 36: 
          { yybegin(YYINITIAL); return symFact.newSymbol("*",Psym.TIMES);
          }
        case 83: break;
        case 20: 
          { return symFact.newSymbol(">",Psym.MOR);
          }
        case 84: break;
        case 25: 
          { return symFact.newSymbol("aFunctionCall",Psym.FUNC, new String(yytext().substring(0,yytext().length() - 1)));
          }
        case 85: break;
        case 27: 
          { return symFact.newSymbol("aString",Psym.STRING, new String(yytext().substring(1,yytext().length() - 1)));
          }
        case 86: break;
        case 40: 
          { return symFact.newSymbol("char",Psym.TYPENAME, new String("char"));
          }
        case 87: break;
        case 32: 
          { return symFact.newSymbol("<=",Psym.LEQ);
          }
        case 88: break;
        case 11: 
          { return symFact.newSymbol("*",Psym.TIMES);
          }
        case 89: break;
        case 16: 
          { return symFact.newSymbol("%",Psym.MOD);
          }
        case 90: break;
        case 6: 
          { return symFact.newSymbol("aVariable",Psym.VARIABLE, new String(yytext()));
          }
        case 91: break;
        case 18: 
          { return symFact.newSymbol("!",Psym.NOT);
          }
        case 92: break;
        case 26: 
          { yybegin(ARRAY1);
                                       identifier = new String(yytext().substring(0,yytext().length() - 1));
                                       return symFact.newSymbol("[",Psym.TIMES);
          }
        case 93: break;
        case 29: 
          { return symFact.newSymbol("++",Psym.INC);
          }
        case 94: break;
        case 30: 
          { return symFact.newSymbol("==",Psym.EQU);
          }
        case 95: break;
        case 42: 
          { return symFact.newSymbol("break",Psym.BREAK);
          }
        case 96: break;
        case 8: 
          { return symFact.newSymbol("-",Psym.MINUS);
          }
        case 97: break;
        case 33: 
          { return symFact.newSymbol(">=",Psym.MEQ);
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return (symFact.newSymbol("EOF",Psym.EOF));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
